### ISSUE TITLE
Table 'cloudlog.options' doesn't exist - Running local environment docker

### ISSUE THREAD

**Issue by mengano-net** [magicbug/Cloudlog#2781]
Hi:

Thanks for open source project; I hope this ticket helps making it better; if it's my mistake, can you please lead me to root cause?

- I followed documentation on wiki, the recommended containerized implementation. Here is my docker-compose.yml file:

```
services:
  cloudlog-mysql:
    image: mysql:latest
    container_name: cloudlog-mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: cloudlog
      MYSQL_USER: cloudlog
      MYSQL_PASSWORD: <sanitized> # <- Insert a strong password here
    # ports:
    #   - "3306:3306" # <- Uncomment these lines only if you need to expose the MySQL container to the network
    volumes:
      - cloudlog-dbdata:/var/lib/mysql
    restart: unless-stopped

  cloudlog-phpmyadmin:
    image: phpmyadmin:latest
    container_name: cloudlog-phpmyadmin
    depends_on:
      - cloudlog-mysql
    environment:
      PMA_HOST: cloudlog-mysql
      PMA_PORT: 3306
      PMA_USER: cloudlog
      PMA_PASSWORD: <sanitized> # <- Put same strong password here
    #restart: unless-stopped
    ports:
      - "8083:80"

  cloudlog-main:
    image: 2m0sql/cloudlog:latest
    container_name: cloudlog-main
    depends_on:
      - cloudlog-mysql
    volumes:
      - cloudlog-config:/var/www/html/application/config
      - cloudlog-backup:/var/www/html/application/backup
      - cloudlog-uploads:/var/www/html/application/uploads
    ports:
      - "8086:80"
    restart: unless-stopped

volumes:
  cloudlog-dbdata:
  cloudlog-config:
  cloudlog-backup:
  cloudlog-uploads:
```

- Upon running `<hostname>/install` I get this error:

```
A PHP Error was encountered
Severity: Warning
Message: Cannot modify header information - headers already sent by (output started at /var/www/html/application/migrations/004_add_eQSL_login_and_url.php:1)
Filename: core/Common.php
Line Number: 575
An uncaught Exception was encountered
Type: mysqli_sql_exception
Message: Table 'cloudlog.options' doesn't exist
Filename: /var/www/html/system/database/drivers/mysqli/mysqli_driver.php
Line Number: 301
```

- Here are my containers running:

```
❯ docker compose ps
NAME                  IMAGE                    COMMAND                  SERVICE               CREATED             STATUS              PORTS
cloudlog-main         2m0sql/cloudlog:latest   "docker-php-entrypoi…"   cloudlog-main         18 minutes ago      Up 18 minutes       0.0.0.0:8086->80/tcp, :::8086->80/tcp
cloudlog-mysql        mysql:latest             "docker-entrypoint.s…"   cloudlog-mysql        18 minutes ago      Up 18 minutes       3306/tcp, 33060/tcp
cloudlog-phpmyadmin   phpmyadmin:latest        "/docker-entrypoint.…"   cloudlog-phpmyadmin   18 minutes ago      Up 18 minutes       0.0.0.0:8083->80/tcp, :::8083->80/tcp
❯
```

- I connected to DB ... Notice the first `show tables;` I ran BEFORE running install script returned empty, then ran it again after I ran `http://<hostname:port>/install` which produced error above. Table seems to exists :(

```
mysql> select * from information_schema.user_privileges where grantee like "'cloudlog'%";
+----------------+---------------+----------------+--------------+
| GRANTEE        | TABLE_CATALOG | PRIVILEGE_TYPE | IS_GRANTABLE |
+----------------+---------------+----------------+--------------+
| 'cloudlog'@'%' | def           | USAGE          | NO           |
+----------------+---------------+----------------+--------------+
1 row in set (0.01 sec)

mysql> show grants for 'cloudlog'@'%';
+--------------------------------------------------------+
| Grants for cloudlog@%                                  |
+--------------------------------------------------------+
| GRANT USAGE ON *.* TO `cloudlog`@`%`                   |
| GRANT ALL PRIVILEGES ON `cloudlog`.* TO `cloudlog`@`%` |
+--------------------------------------------------------+
2 rows in set (0.00 sec)

mysql> show tables;
Empty set (0.00 sec)

mysql> show tables;
+------------------------+
| Tables_in_cloudlog     |
+------------------------+
| TABLE_HRD_CONTACTS_V01 |
| api                    |
| cat                    |
| config                 |
| dxcc_entities          |
| dxcc_exceptions        |
| dxcc_prefixes          |
| migrations             |
| notes                  |
| options                |
| station_profile        |
| timezones              |
| users                  |
+------------------------+
13 rows in set (0.00 sec)

mysql> desc options;
+--------------+-----------------+------+-----+---------+----------------+
| Field        | Type            | Null | Key | Default | Extra          |
+--------------+-----------------+------+-----+---------+----------------+
| option_id    | bigint unsigned | NO   | PRI | NULL    | auto_increment |
| option_name  | varchar(191)    | YES  | UNI | NULL    |                |
| option_value | longtext        | NO   |     | NULL    |                |
| autoload     | varchar(20)     | YES  |     | NULL    |                |
+--------------+-----------------+------+-----+---------+----------------+
4 rows in set (0.00 sec)

mysql>
```

- If you send me a `CREATE|ALTER TABLE` command, I can run it and re-try `http://<hostname>:port/install`
